name: Upload Package to TestPyPI/PyPI

on:
  push:
    branches:
      main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        cache: 'pip'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        # python3 -m pip install -r requirements.txt
        python3 -m pip install setuptools wheel twine build

    - name: Build
      run: |
        python3 setup.py sdist bdist_wheel
        # python -m build --sdist --wheel --outdir dist/ .
        twine check dist/*

    - name: Publish to Test PyPI
      run: |
        twine upload -r testpypi -u __token__ -p ${{ secrets.TESTPYPI_TOKEN }} --non-interactive dist/*

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: |
        twine upload -r pypi -u __token__ -p ${{ secrets.PYPI_PASSWORD }} --non-interactive dist/*